### ISSUE TITLE
Check native support for charset UTF-8

### ISSUE THREAD

**Issue by rolfsimoes** [Open-Earth-Monitor/openeocraft#24]
Links to #14 

Check if `plumber` and R natively (and it HTTP server) supports charset UTF-8 for all requests and responses.
Please, provide some references.

**Comment by PondiB** [comment]
> Check if `plumber` and R natively (and it HTTP server) supports charset UTF-8 for all requests and responses.
> Please, provide some references.

by default, R itself supports UTF-8 encoding i.e. [1](https://developer.r-project.org/WindowsBuilds/winutf8/winutf8.html#:~:text=Hence%2C%20R%20supports%20UTF%2D8,converted%20to%20the%20native%20encoding) and [2](https://blog.r-project.org/2021/12/07/upcoming-changes-in-r-4.2-on-windows/)

Since Plumber relies on R's capabilities for handling strings and encoding, it inherently supports UTF-8 for all requests and responses[3](https://github.com/rstudio/plumber/blob/main/R/utf8.R)
